import json
import logging
import time
import sys
sys.path.append('./')
import VINResolver

"""
Valid NA/US VIN (validvin = true): 1FAHP26W49G252740
Invalid NA/US VIN (validvin = false): 1FAHP26W49G252788
Invalid NA/Canada VIN (validvin = false): 2WMCGH3B2CES5C8T2
Valid NA/Canada VIN (validvin = true): 2WMCGH3B5CES5C8T2
Valid Asia/Japan VIN (validvin = true): JN1CV6EP0A0013908
Valid EU/Germany VIN (validvin = true): WDBJF65J71B325157
Invalid VINs (validvin = false): XXXCV6EP0A00139089, WDBJF65J71B3251579
Invalid Chinese VIN (validvin = false): LDNCGH3B2CES5C8T2
Valid Chinese VIN (validvin = true): LDNCGH3B5CES5C8T2

"""

test_query = [
    'willem bravo yankie gee vier dreie dänemark zürich xaver bernd petra juliett drei viktor nordpol sieben mike ist mein vin',
    'UU3HV8SKX9U2FECFV ist mein fahrzeugidentnummer.',
    'acht alex paris dieter lima siebene ypsilon udin jerusalem florida chiasso null mike rosa fünf bertram leopold genau',
    'VG5ADJR2T2JZV64AD genau',
    'SJNA4YWU3WBFJTXZ7 ist mein fahrzeugidentnummer.',
    'eins zulu victor kaiser romeo elektrisch charlotte ypsilon einse konrad paula zwei xanthippe xylophon upsala cärsa xray ja',
    'TSBB65XPVL55G14J6 ja',
    'x-ray viere x-ray liverpool kilo marie tango werner sechse elektroauto siebene null gustav x-ray tristan zoro zulu ist mein vin',
    'ludwig florida papa november chiasso eins sechse christoph null siebene tripoli dora sechse foxtrot romeo dreie ein ist mein vin',
    'fünfe yankie friedrich vier acht erhard viktor mike siebene florida willem bertha charly november neun vier jakob ist das.',
    'zwei golf norbert charlie fünfe hotel dreie richard siebene dieter achte ludwig wilhelm x-ray golf edison cerca ist das.',
    '3GC3RNGK7DD3HA3VN genau',
    'neune bertram willem acht november null havana wilhelm zoro drei viktor gustav ypsilon valencia julius petra jan ist mein vin',
    '2FM5TMRU8HEZRLGHR ist mein fahrzeugidentnummer.',
    'MR03UV0D1JAL1NXBE ist mein fahrzeugidentnummer.',
    'sophie charly florida berta sechs yankie udin gallipoli neun viere kaufmann paula achte historisch acht dreie neun genau',
    'valencia stefan sechse zorro papa zoro sieben kilo mercedes juliet heinrich dreie valencia dreie helmut norbert sechs genau',
    'siegfried christine charlotte tim bravo neun petra kaiser ein eins ein delta zwo null ludwig sechs golf ist mein fahrzeugidentnummer.',
    'marie marta amsterdam kaufmann dreie ypsilon vier dreie yverdon willem petra november elektrisch neune null willem acht genau',
    'viktor foxtrot neune romeo vier err vier wilhelm wilhelm foxtrott paula romeo sechs victor erika viktor südpol ist mein vin',
    'siegfried liverpool peter fünfe zeppelin ebert friedrich christine yverdon martin sierra kaufmann jan siebene ein dora paula ist das.',
    'mercedes alex bernd luxemburg ludwig acht karl sechse albert madagaskar gee helmut einse xaver emil yverdon daniel ist das.',
    'WKK3NH8XKBHM0KRBE ist das.',
    'WCDFVB6AMVK9MAMA0 ist mein vin',
    'TN9ATJTLCV8FYNGJE genau',
    '1G8DV1AD3V3Z4Z2JM genau',
    '4A4JH11T9MLCTBUXG ist das.',
    'MNT278Z6SWYJXT7CD ist das.',
    '6G283F0LSMPJ353S1 ist das.',
    'xaver tim yankie martin yankee paris paris sechse fünfe alex null bernd viere cärsa anton marie drei ist mein fahrzeugidentnummer.',
    'fünf norbert papa dänemark delta xray xray zeppelin null sophie alex ebert viere null sieben benz elektroauto ist mein vin',
    'mike bernd eins fünf leopold tango yankie zürich benz foxtrott fünf yverdon richard null eins drei sechse ist mein fahrzeugidentnummer.',
    '4A3JT52K55D0DY0Z5 ist das.',
    'einse marie neune err charlie alex tristan drei neune viere jerusalem charlie zulu err uniform zoro foxtrott ist mein vin',
    '1M37PXNN1M0JEHB40 ist das.',
    'paula echo eins liverpool victor siebene fünfe fünfe zeppelin bravo whiskey fünfe lima victor karl emil null ist mein vin',
    'siebene neun fünfe papa xylophon tim kilogramm golf xylophon zwo baltimore yankie einse romeo zweie zorro siebene genau',
    'SU99EPSR7YF124T1H ist mein fahrzeugidentnummer.',
    '1HD01M7P2SP84NKHV ja',
    'luxemburg viktor siegfried marta gee gustav amsterdam gustav fünfe rosa historisch kilo daniel neun sechse vier anton ist mein vin',
    'fünf yankee friedrich juliett valencia helmut xaver upsala vier kilogramm kilo ludwig victor richard dreie zwei drei ist mein vin',
    'WDPDNE8BLEJJLSKZ2 ist mein vin',
    'vier victor fünf elektrisch theodor madagaskar neun martha eins xaver null südpol sechse willem zweie edison acht ist mein vin',
    'sechse foxtrot papa anna gustav tristan cäsar achte yankee fünfe einse einse ein richard erich yokohama neun ist mein fahrzeugidentnummer.',
    'victor foxtrot acht viktor fünf kilo zwei fünfe zweie sieben bernd leopold zulu werner dieter new york zwo ist mein fahrzeugidentnummer.',
    'MB8GFV5DJ7ZV9X0DL ist mein vin',
    'MAT3GRAR9WA6DNR79 ist mein fahrzeugidentnummer.',
    '5JL8ABMJ026EWMHS1 genau',
    'JMZEFCP9GC1Z9BMGL genau',
    '2BP59B053B8H7F1PM ist das.',
    'VG5603F044ZWB7KJW ist das.',
    'yankie benz werner yankee null viktor erhard uniform zeppelin siegfried zweie acht null vier xray helmut kaufmann ja',
    'LB24G1CV4JG44HN4N genau',
    'wilhelm ulrich albert alfa niklaus golf acht victor elektrisch erika erhard wilhelm xanthippe willem drei friedrich eins ist mein fahrzeugidentnummer.',
    'werner anton ein florida ein theodor ein florida acht eins drei historisch achte golf bravo zweie tripoli ist mein vin',
    'SU94YXF73CLF10Y70 genau',
    'zwei friedrich bertha bernd viere karl havana november acht xray petra zoro ulrich mike x-ray einse friedrich ist mein vin',
    '1G4TTPFS9HMF6HWN8 ist das.',
    'JFKNHWCKFP8XXXRYD ist mein vin',
    '6F4VZUPEKSHA1XG3B ist mein vin',
    'acht anton konrad cerca anton viere sieben neune sieben sechs valencia zeppelin sechs petra jerusalem zwo sieben ja',
    'victor florida drei washington neune anton kaufmann elektro jan juliet lima xylophon peter sieben siebene lima liverpool ja',
    '3GND56YD5PCFYBLBF ist mein fahrzeugidentnummer.',
    'KNBKJJ8TDK97SDJ7M genau',
    'achte alex daimler november tripoli tripoli sophie amsterdam ludwig werner kaufmann whiskey achte ypsilon mike dreie südpol ist das.',
    'SKFJYE7NSCG4YSJ23 ist das.',
    'LTP80M9L95JX4J1PZ ist mein fahrzeugidentnummer.',
    'valencia foxtrott sechs viere dreie tango paula sieben erhard daniel zacharias washington kilo karl golf zweie benz ist mein fahrzeugidentnummer.',
    'ein gallipoli baltimore christine erhard marta jakob marta sieben anton werner delta roma hotel zorro fünfe konrad genau',
    'SCKEUU1ETSXF1VCFL genau',
    'wilhelm martin elektroauto zweie roma sechse neun sierra anna luxemburg upsala christian elektroauto marta tripoli udin zwo ist mein fahrzeugidentnummer.',
    'luxemburg acht xylophon cerca drei ebert tripoli historisch xylophon achte sechs gallipoli benz null sophie dreie alfa ist mein vin',
    'juliet helmut zorro x-ray fünf zwei zwei dieter golf romeo golf neune viere mike amerika martin marie ist mein vin',
    'WVWFGSXZK8JYKBSFU ist mein vin',
    'siebene neune fünfe yverdon karl valencia valencia neun achte sierra null charlie willem null leopold xylophon bravo ist das.',
    '3GZ99FVH2W1MCE20Z ist mein fahrzeugidentnummer.',
    '1L29501K6XHAY2BFF ist das.',
    'LET06SG65H6T9Y60Y ist das.',
    '2CN5WSNC79DCRTZ2Z genau',
    '5J6LFKCN17P9VK4NB ist mein vin',
    'kilo norbert christopher historisch richard null acht err valencia neun ebert ein ein eins uniform viktor neun ist mein fahrzeugidentnummer.',
    'NAAUA7SSAG1VBJS6F ist mein vin',
    'lima bertha papa viere tristan siebene casablanca alex null historisch paris victor elektrisch johann mercedes dieter nikolaus ist mein vin',
    'julius havana new york paula cärsa dreie sieben bertram nikolaus elektroauto zacharias udin sechs foxtrot drei golf err genau',
    'acht gustav dora xray achte x-ray edison santiago foxtrott niklaus cäsar einse deutschland luxemburg charlotte sieben null ist mein vin',
    'wilhelm martha whiskey achte theodor ypsilon kaufmann zorro leopold fünf martha neune valencia eins vier neun washington ist mein vin',
    'achte alpha peter drei roma null kaiser null tango viktor yokohama zwo fünf gustav eins zürich amsterdam ist mein fahrzeugidentnummer.',
    '4V6P4TM69C5HAPAR6 genau',
    'ludwig charlie erhard casablanca nordpol zeppelin kilo liverpool null eins null cäsar uniform christine hotel historisch whiskey ist mein fahrzeugidentnummer.',
    'mike paula alex christopher ypsilon alex viere yverdon udin julius uniform neune luxemburg yankie christian dreie sechse ist das.',
    'marie stefan null juliet luxemburg viere acht deutschland samuel golf viere edison golf neun ludwig norbert achte ist mein vin',
    'victor luxemburg uniform sechse elektro zwei einse sieben richard golf dreie zweie achte siebene dieter florida zwei ja',
    'sechse helmut achte petra valencia zwo luxemburg deutschland havana gustav november ludwig sechse washington zwei kilo null ist mein fahrzeugidentnummer.',
    'julius florida hotel kaiser sieben zwei golf tim konrad karl kilo zoro viktor drei anja null gallipoli ist das.',
    '3MDMYRKG2XX70LKRL ja',
    '8AFCT43HZ3TAD6EUA ist das.',
    'willem papa null gee marta christine fünf foxtrot kaiser neune gallipoli karl leopold juliet udin xanthippe neun ist mein fahrzeugidentnummer.',
    'VF72AZG4WHZUS1YD2 ist mein fahrzeugidentnummer.',
    'fünf acht amsterdam ulrich ebert viktor kilogramm neune null christine hotel ludwig gustav yokohama golf foxtrot bernd ist mein fahrzeugidentnummer.',
    'lima martin cerca erhard tango sechse foxtrott richard sechs friedrich daniel südpol golf marta dora hotel luxemburg ja'
    ]

test_vin = [
    'WBYG43DZXBPJ3VN7M',
    'UU3HV8SKX9U2FECFV',
    '8APDL7YUJFC0MR5BL',
    'VG5ADJR2T2JZV64AD',
    'SJNA4YWU3WBFJTXZ7',
    '1ZVKRECY1KP2XXUCX',
    'TSBB65XPVL55G14J6',
    'X4XLKMTW6E70GXTZZ',
    'LFPNC16C07TD6FR31',
    '5YF48EVM7FWBCN94J',
    '2GNC5H3R7D8LWXGEC',
    '3GC3RNGK7DD3HA3VN',
    '9BW8N0HWZ3VGYVJPJ',
    '2FM5TMRU8HEZRLGHR',
    'MR03UV0D1JAL1NXBE',
    'SCFB6YUG94KP8H839',
    'VS6ZPZ7KMJH3V3HN6',
    'SCCTB9PK111D20L6G',
    'MMAK3Y43YWPNE90W8',
    'VF9R4R4WWFPR6VEVS',
    'SLP5ZEFCYMSKJ71DP',
    'MABLL8K6AMGH1XEYD',
    'WKK3NH8XKBHM0KRBE',
    'WCDFVB6AMVK9MAMA0',
    'TN9ATJTLCV8FYNGJE',
    '1G8DV1AD3V3Z4Z2JM',
    '4A4JH11T9MLCTBUXG',
    'MNT278Z6SWYJXT7CD',
    '6G283F0LSMPJ353S1',
    'XTYMYPP65A0B4CAM3',
    '5NPDDXXZ0SAE407BE',
    'MB15LTYZBF5YR0136',
    '4A3JT52K55D0DY0Z5',
    '1M9RCAT394JCZRUZF',
    '1M37PXNN1M0JEHB40',
    'PE1LV755ZBW5LVKE0',
    '795PXTKGX2BY1R2Z7',
    'SU99EPSR7YF124T1H',
    '1HD01M7P2SP84NKHV',
    'LVSMGGAG5RHKD964A',
    '5YFJVHXU4KKLVR323',
    'WDPDNE8BLEJJLSKZ2',
    '4V5ETM9M1X0S6W2E8',
    '6FPAGTC8Y5111REY9',
    'VF8V5K2527BLZWDN2',
    'MB8GFV5DJ7ZV9X0DL',
    'MAT3GRAR9WA6DNR79',
    '5JL8ABMJ026EWMHS1',
    'JMZEFCP9GC1Z9BMGL',
    '2BP59B053B8H7F1PM',
    'VG5603F044ZWB7KJW',
    'YBWY0VEUZS2804XHK',
    'LB24G1CV4JG44HN4N',
    'WUAANG8VEEEWXW3F1',
    'WA1F1T1F813H8GB2T',
    'SU94YXF73CLF10Y70',
    '2FBB4KHN8XPZUMX1F',
    '1G4TTPFS9HMF6HWN8',
    'JFKNHWCKFP8XXXRYD',
    '6F4VZUPEKSHA1XG3B',
    '8AKCA47976VZ6PJ27',
    'VF3W9AKEJJLXP77LL',
    '3GND56YD5PCFYBLBF',
    'KNBKJJ8TDK97SDJ7M',
    '8ADNTTSALWKW8YM3S',
    'SKFJYE7NSCG4YSJ23',
    'LTP80M9L95JX4J1PZ',
    'VF643TP7EDZWKKG2B',
    '1GBCEMJM7AWDRHZ5K',
    'SCKEUU1ETSXF1VCFL',
    'WME2R69SALUCEMTU2',
    'L8XC3ETHX86GB0S3A',
    'JHZX522DGRG94MAMM',
    'WVWFGSXZK8JYKBSFU',
    '795YKVV98S0CW0LXB',
    '3GZ99FVH2W1MCE20Z',
    '1L29501K6XHAY2BFF',
    'LET06SG65H6T9Y60Y',
    '2CN5WSNC79DCRTZ2Z',
    '5J6LFKCN17P9VK4NB',
    'KNCHR08RV9E111UV9',
    'NAAUA7SSAG1VBJS6F',
    'LBP4T7CA0HPVEJMDN',
    'JHNPC37BNEZU6F3GR',
    '8GDX8XESFNC1DLC70',
    'WMW8TYKZL5M9V149W',
    '8AP3R0K0TVY25G1ZA',
    '4V6P4TM69C5HAPAR6',
    'LCECNZKL010CUCHHW',
    'MPACYA4YUJU9LYC36',
    'MS0JL48DSG4EG9LN8',
    'VLU6E217RG3287DF2',
    '6H8PV2LDHGNL6W2K0',
    'JFHK72GTKKKZV3A0G',
    '3MDMYRKG2XX70LKRL',
    '8AFCT43HZ3TAD6EUA',
    'WP0GMC5FK9GKLJUX9',
    'VF72AZG4WHZUS1YD2',
    '58AUEVK90CHLGYGFB',
    'LMCET6FR6FDSGMDHL'
    ]

start =  time.time()
errors = []
for query, vin in zip(test_query, test_vin):
    try:
        res, status_code = VINResolver.test_VINResolver(query)
        resVIN = res['vinQuery'].upper()
        if resVIN != vin.upper():
            logging.warning(f'[ERROR] VIN mismatch for {query} -> {vin} != {resVIN}')
            errors.append(query)
    except Exception as e:
        logging.warning(query, e, res)
        errors.append(query)

end = time.time() - start

logging.warning(f'[INFO] DONE -> {1 - (len(errors)/len(test_query)):.2%}. \n\tTotal duration \t\t{end:.3}s \n\tDuration per loop \t{end/len(test_query):.3}s')