# Attribute Validators
CONFIG = "config"
MANIFEST = "manifest"
MODULES = "modules"
USE_DB = "use_db"
LOCAL_DATA_PATH = "local_data_path"

MODULE = "module"
INPUT = "input"
LOCALES = "locales"
REGION = "region"
VALUES = "values"

ATTRIBUTE_VALIDATOR = "AttributeValidator"
ATTRIBUTE_VALIDATOR_ENV = "ATTRIBUTE_VALIDATOR"
ATTRIBUTE_VALIDATOR_CITY_TABLE = "AttributeValidatorZIP"
ATTRIBUTE_VALIDATOR_ADDRESS_TABLE = "AttributeValidatorStreets"
ADDRESS = "address"
CITY = "city"
HOUSE_NUMBER = "number"
IBAN = "iban"
STREET = "street"
STREET_IN_CITY = "street_in_city"
ZIP = "zip"

LEV_DISTANCE_INIT = 2

CUSTOMER_DATA_TABLE = "CustomerData"

ATTRIBUTE_LOOKUP_ZIP = "ZIP"
ATTRIBUTE_LOOKUP_STREET = "RowKey"

AUTHENTICATOR = "Authenticator"
AUTHENTICATOR_ENV = "AUTHENTICATOR"
FORM_REGOGNIZER_ENV = "FORM_RECOGNIZER"
LICENSE_PLATE_RECOGNIZER = "LicensePlateRecognizer"
LICENSE_PLATE_RECOGNIZER_ENV = "LICENSE_PLATE_RECOGNIZER"
TABLE_REQUESTOR = "TableRequestor"
TABLE_REQUESTOR_ENV = "TABLE_REQUESTOR"
VIN_RESOLVER = "VINResolver"
VIN_RESOLVER_ENV = "VIN_RESOLVER"

SETTINGS_LOOKUP = {
    AUTHENTICATOR_ENV:              ["CONNECTION_STRING"],
    ATTRIBUTE_VALIDATOR_ENV:        ["CONNECTION_STRING"],
    FORM_REGOGNIZER_ENV:            ["FR_NAME", "FR_TABLE_NAME", "FR_STORAGE_CONNECTION_STRING", "FR_RETURN_KEYS"],
    LICENSE_PLATE_RECOGNIZER_ENV:   ["CONNECTION_STRING", "LUIS_ID_{region_code}", "LUIS_ID_{region_code}", "LUIS_KEY_{region_code}", "LUIS_PREDICTION_ENDPOINT_{region_code}", "LUIS_SLOT_{region_code}"],
    TABLE_REQUESTOR_ENV:            ["CONNECTION_STRING"],
    VIN_RESOLVER_ENV:               ["LUIS_ID_{region_code}", "LUIS_KEY_{region_code}", "LUIS_PREDICTION_ENDPOINT_{region_code}", "LUIS_SLOT_{region_code}"],
}